services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres_gestao_viagens
    volumes:
      - ./data:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_viagens